project:
  type: website

website:
  title: "Mark Girard"
  navbar:
    logo: profile.jpg
    background: dark
    left:
      - about.qmd
      - mathblog.qmd
    right:
      - icon: github
        href: https://github.com/markwgirard
      - icon: linkedin
        href: https://www.linkedin.com/in/markwgirard/
  sidebar:
    style: docked
    logo: profile.jpg
    border: false
    background: dark
    foreground: gray-600
    alignment: left
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: mathblog.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Miscellaneous"
        href: miscllaneous.qmd
  page-footer:
    left: "© Copyright 2023 Mark Girard."
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

comments:
  giscus:
    repo: markwgirard/markwgirard.github.io

